name: "CodeDeviation"
description: "Write code that deviates from standard"

url: "http://localhost:4000"

paginate: 5

markdown: rdiscount
permalink: /:categories/:year/:month/:day/:title/
highlighter: pygments
